# Generated by Django 4.0.6 on 2022-11-10 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='post',
            new_name='position',
        ),
    ]
