# Generated by Django 4.0.6 on 2022-11-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_rename_post_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='state',
            new_name='region',
        ),
    ]
