# Generated by Django 4.0.6 on 2022-11-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0004_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='empcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
