# Generated by Django 4.0.6 on 2023-01-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_features', '0003_rename_base_salary_salary_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='days_logged_in',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
