# Generated by Django 4.0.6 on 2023-01-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_features', '0004_salary_bonus_alter_salary_days_logged_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='days_logged_in',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
