# Generated by Django 4.0.6 on 2023-01-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_features', '0007_alter_salary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='working_days',
            field=models.IntegerField(),
        ),
    ]
