# Generated by Django 4.0.6 on 2023-01-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_features', '0008_alter_salary_base_salary_alter_salary_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
