# Generated by Django 4.0.6 on 2023-01-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_features', '0009_alter_salary_base_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='working_days',
            field=models.IntegerField(default=0),
        ),
    ]
